"""add activity_location to Table Posts

Revision ID: 127e6a09b59
Revises: 72695a013b
Create Date: 2016-08-02 10:08:46.846232

"""

# revision identifiers, used by Alembic.
revision = '127e6a09b59'
down_revision = '72695a013b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('activity_location', sa.VARCHAR(length=40), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'activity_location')
    ### end Alembic commands ###
