"""add Carpool and Passenger tables

Revision ID: 1a559f9fbc0
Revises: 573e8e43fbb
Create Date: 2016-07-19 11:31:33.039656

"""

# revision identifiers, used by Alembic.
revision = '1a559f9fbc0'
down_revision = '573e8e43fbb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carpools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('driver', sa.VARCHAR(length=50), nullable=True),
    sa.Column('contact', sa.VARCHAR(length=200), nullable=True),
    sa.Column('source', sa.VARCHAR(length=50), nullable=False),
    sa.Column('destination', sa.VARCHAR(length=50), nullable=False),
    sa.Column('departure_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('notice', sa.VARCHAR(length=200), nullable=True),
    sa.Column('max_people', sa.SMALLINT(), nullable=True),
    sa.Column('people_count', sa.SMALLINT(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('passengers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('carpool_id', sa.Integer(), nullable=False),
    sa.Column('join_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('contact', sa.VARCHAR(length=200), nullable=True),
    sa.ForeignKeyConstraint(['carpool_id'], ['carpools.id'], ),
    sa.ForeignKeyConstraint(['uid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('passengers')
    op.drop_table('carpools')
    ### end Alembic commands ###
