"""empty message

Revision ID: 26829790a88
Revises: 3db3f3ceda5
Create Date: 2016-05-26 12:29:37.968233

"""

# revision identifiers, used by Alembic.
revision = '26829790a88'
down_revision = '3db3f3ceda5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('source', sa.VARCHAR(length=20), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'source')
    ### end Alembic commands ###
