"""add level field to User table

Revision ID: 573e8e43fbb
Revises: 26829790a88
Create Date: 2016-07-07 11:14:33.551077

"""

# revision identifiers, used by Alembic.
revision = '573e8e43fbb'
down_revision = '26829790a88'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('level', sa.SMALLINT(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'level')
    ### end Alembic commands ###
